# Generated by Django 6.0.6 on 2026-06-04 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Isla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_isla', models.PositiveIntegerField(unique=True)),
                ('equipos_computo', models.PositiveIntegerField()),
                ('switches', models.PositiveIntegerField(default=0)),
                ('routers', models.PositiveIntegerField(default=0)),
                ('otros_componentes', models.JSONField(blank=True, default=dict)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada')], default='Disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['numero_isla'],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_horas', models.PositiveIntegerField(default=1)),
                ('hora_escaneo_inicio', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL)),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='isla_control.isla')),
            ],
            options={
                'ordering': ['-fecha_reserva', '-hora_inicio'],
            },
        ),
    ]
