# Generated by Django 6.0.4 on 2026-07-29 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isla_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, default='Mantenimiento', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_bloqueados_creados', to=settings.AUTH_USER_MODEL)),
                ('isla', models.ForeignKey(blank=True, help_text='Si es null, aplica a todas las islas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='isla_control.isla')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
