# Generated by Django 6.0.4 on 2026-10-06 18:34

import django.core.validators
from django.db import migrations, models



def clave_isc(apps, schema_editor):
    """La carrera de Sistemas queda con clave ISC; las demás las registra el admin."""
    Carrera = apps.get_model('users', 'Carrera')
    Carrera.objects.filter(nombre__iexact='Ingeniería en Sistemas Computacionales', clave__isnull=True).update(clave='ISC')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='clave',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cuatrimestre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grupo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.RunPython(clave_isc, migrations.RunPython.noop),
    ]
