# Generated by Django 6.0.4 on 2026-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=1)),
                ('max_stock', models.PositiveIntegerField(default=200)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible'), ('Danado', 'Dañado'), ('En reparación', 'En reparación'), ('En préstamo', 'En préstamo')], default='Disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
