# Generated by Django 6.0.4 on 2026-09-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha límite de entrega', null=True),
        ),
    ]
