# Generated by Django 6.0.4 on 2026-09-25 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def activate_latest_term(apps, schema_editor):
    """El cuatrimestre existente con id más alto queda activo; las fechas las pone el admin."""
    Term = apps.get_model('academic', 'Term')
    latest = Term.objects.order_by('-id').first()
    if latest:
        Term.objects.filter(pk=latest.pk).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('festivo', 'Festivo'), ('examenes', 'Exámenes'), ('evento', 'Evento')], default='evento', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(activate_latest_term, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_term'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='academic.term'),
        ),
    ]
