# Generated by Django 6.0.4 on 2026-10-06 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_term_dates_calendar_events'),
        ('users', '0002_carrera_clave_cohorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='users.carrera'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='cuatrimestre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='grupo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
