# Generated by Django 6.0.6 on 2026-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_loan_id', models.IntegerField(blank=True, null=True)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_by_username', models.CharField(max_length=150)),
                ('approved_by_username', models.CharField(max_length=150)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('loan_period_days', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-approval_date'],
            },
        ),
    ]
