# Generated by Django 6.0.4 on 2026-05-25 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialloan',
            name='has_condition_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='condition_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition_report', to='loans.materialloan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
