# Generated by Django 6.0.4 on 2026-07-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='condition_reports/'),
        ),
    ]
