# Generated by Django 6.0.4 on 2026-09-23 02:08

from django.db import migrations, models


def set_initial_status(apps, schema_editor):
    MaterialLoan = apps.get_model('loans', 'MaterialLoan')
    MaterialLoan.objects.filter(has_condition_report=True).update(status='Finalizado')
    MaterialLoan.objects.filter(has_condition_report=False, approved_by__isnull=False).update(status='Autorizado')


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_conditionreport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialloan',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Autorizado', 'Autorizado'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.RunPython(set_initial_status, migrations.RunPython.noop),
    ]
